### ISSUE TITLE
Hi! 

### ISSUE THREAD

**Issue by konstantinkurenkov** [taichi-ishitani/tvip-axi#7] opened 2019-06-26 15:10 UTC
I have a problem with randomize().  Is it problem with my linux or something else?    
When i use rendomize() in my project i don't have such error...

terminal output   ------------------------------------------------------------------------>

if (!item.randomize() with {
                      |
xmsim: *W,SVRNDF (/home/tvip-axi/src/tvip_axi_slave_default_sequence.svh,59|22): The randomize method call failed. The unique id of the failed randomize call is 23.
xmsim: *F,RNDUNR: Randomization internal error, unexpected exception - 18rnc_eval_exception#6934
  File - /dv/p4Cusers01nd/dvcmin_noida_legacy_rc_xcelium_092718_170012_linux/tbv/rnc/src/api/rnc_var.cpp:1977
    var -   SO =   2,  U31, flags =     ZESA, _value = 0x00000000 : data.size#5536 (/home/tvip-axi/src/tvip_axi_slave_default_sequence.svh, 59).

**Comment by konstantinkurenkov** [comment] 2019-06-26 15:23
I think i understand what is the problem. it's my fault

**Comment by taichi-ishitani** [comment] 2019-06-27 01:18
Hi @konstantinkurenkov ,
Thank you for opening the issue.
Have you resolved the issue? What is the cause of the issue?

**Comment by konstantinkurenkov** [comment] 2019-06-27 06:16
I can't resolve this iisue now, but i suppose the reason connected with my operation system.
I checked your project in two servers but the result equal - The randomize method call failed.

i have CentOS on my server machine.

**Comment by taichi-ishitani** [comment] 2019-06-27 08:19
Thanks for the update.
I think it is better that you ask Cadence support.

BTW, what version of Xcelium do you use?
I used Xcelium 18.09 version when I tried to use my VIP on Xcelium simulator.
 I also think it is better that you use this version if you can.

**Comment by taichi-ishitani** [comment] 2019-06-27 08:43
Can you apply the patch below to `src/tvip_axi_item.svh` and try again?

```patch
diff --git a/src/tvip_axi_item.svh b/src/tvip_axi_item.svh
index 5774f4e..5ca9beb 100644
--- a/src/tvip_axi_item.svh
+++ b/src/tvip_axi_item.svh
@@ -287,11 +287,9 @@ endclass
 
 class tvip_axi_slave_item extends tvip_axi_item;
   constraint c_valid_data {
-    if (access_type == TVIP_AXI_READ_ACCESS) {
-      data.size() == burst_length;
-      foreach (data[i]) {
-        (data[i] >> this.configuration.data_width) == 0;
-      }
+    data.size() == burst_length;
+    foreach (data[i]) {
+      (data[i] >> this.configuration.data_width) == 0;
     }
   }
 
@@ -372,6 +370,7 @@ class tvip_axi_slave_item extends tvip_axi_item;
     burst_type.rand_mode(0);
     if (access_type == TVIP_AXI_WRITE_ACCESS) begin
       data.rand_mode(0);
+      c_valid_data.constraint_mode(0);
     end
     strobe.rand_mode(0);
     write_data_delay.rand_mode(0);

```

**Comment by konstantinkurenkov** [comment] 2019-06-27 08:43
I use Xcelium 17.10 and a don't have opportunity use different version

**Comment by konstantinkurenkov** [comment] 2019-06-27 08:56
> Can you apply the patch below to `src/tvip_axi_item.svh` and try again?
> 
> ```diff
> diff --git a/src/tvip_axi_item.svh b/src/tvip_axi_item.svh
> index 5774f4e..5ca9beb 100644
> --- a/src/tvip_axi_item.svh
> +++ b/src/tvip_axi_item.svh
> @@ -287,11 +287,9 @@ endclass
>  
>  class tvip_axi_slave_item extends tvip_axi_item;
>    constraint c_valid_data {
> -    if (access_type == TVIP_AXI_READ_ACCESS) {
> -      data.size() == burst_length;
> -      foreach (data[i]) {
> -        (data[i] >> this.configuration.data_width) == 0;
> -      }
> +    data.size() == burst_length;
> +    foreach (data[i]) {
> +      (data[i] >> this.configuration.data_width) == 0;
>      }
>    }
>  
> @@ -372,6 +370,7 @@ class tvip_axi_slave_item extends tvip_axi_item;
>      burst_type.rand_mode(0);
>      if (access_type == TVIP_AXI_WRITE_ACCESS) begin
>        data.rand_mode(0);
> +      c_valid_data.constraint_mode(0);
>      end
>      strobe.rand_mode(0);
>      write_data_delay.rand_mode(0);
> ```

Yes! Your code help me! Thank you!

**Comment by taichi-ishitani** [comment] 2019-06-27 14:21
Does this patch solve your issue?
Currently, I cannot use Xcelium so I'm not sure that this patch work well.

**Comment by konstantinkurenkov** [comment] 2019-06-27 14:40
the result of your example 
---------------------------------------------------------------------------------
-- UVM Report catcher Summary ---


Number of demoted UVM_FATAL reports  :    0
Number of demoted UVM_ERROR reports  :    0
Number of demoted UVM_WARNING reports:    0
Number of caught UVM_FATAL reports   :    0
Number of caught UVM_ERROR reports   :    0
Number of caught UVM_WARNING reports :    0

--- UVM Report Summary ---

** Report counts by severity
UVM_INFO :    3
UVM_WARNING :    0
UVM_ERROR :    0
UVM_FATAL :    0
** Report counts by id
[RNTST]     1
[SRANDOM]     1
[uvm_test_top]     1
Simulation complete via $finish(1) at time 7214500 PS + 91

**Comment by taichi-ishitani** [comment] 2019-06-27 15:16
Thanks for the update. It seems that this patch works well.
I will commit this change and close this ticket.
Feel free to open to open a new ticket if you have any question, problem, request !

**Closed** 2019-06-27 15:32 UTC
Labels: good first issue
